/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SignupRouteImport } from "./routes/signup";
import { Route as SellerRouteImport } from "./routes/seller";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as ForbiddenRouteImport } from "./routes/forbidden";
import { Route as AdminRouteImport } from "./routes/admin";
import { Route as AuthedRouteImport } from "./routes/_authed";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ProductsIndexRouteImport } from "./routes/products/index";
import { Route as DropsIndexRouteImport } from "./routes/drops/index";
import { Route as AdminIndexRouteImport } from "./routes/admin/index";
import { Route as SellerSettlementsRouteImport } from "./routes/seller/settlements";
import { Route as ProductsIdRouteImport } from "./routes/products/$id";
import { Route as DropsIdRouteImport } from "./routes/drops/$id";
import { Route as AdminSettlementsRouteImport } from "./routes/admin/settlements";
import { Route as AdminCategoriesRouteImport } from "./routes/admin/categories";
import { Route as AuthedMypageRouteImport } from "./routes/_authed/mypage";
import { Route as SellerProductsIndexRouteImport } from "./routes/seller/products/index";
import { Route as AuthedOrdersIndexRouteImport } from "./routes/_authed/orders/index";
import { Route as SellerProductsNewRouteImport } from "./routes/seller/products/new";
import { Route as SellerProductsIdRouteImport } from "./routes/seller/products/$id";
import { Route as AuthedCheckoutOrderIdRouteImport } from "./routes/_authed/checkout/$orderId";
import { Route as AuthedOrdersOrderIdIndexRouteImport } from "./routes/_authed/orders/$orderId/index";
import { Route as AuthedOrdersOrderIdCompleteRouteImport } from "./routes/_authed/orders/$orderId/complete";

const SignupRoute = SignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRouteImport,
} as any);
const SellerRoute = SellerRouteImport.update({
  id: "/seller",
  path: "/seller",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: "/forbidden",
  path: "/forbidden",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedRoute = AuthedRouteImport.update({
  id: "/_authed",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: "/products/",
  path: "/products/",
  getParentRoute: () => rootRouteImport,
} as any);
const DropsIndexRoute = DropsIndexRouteImport.update({
  id: "/drops/",
  path: "/drops/",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminRoute,
} as any);
const SellerSettlementsRoute = SellerSettlementsRouteImport.update({
  id: "/settlements",
  path: "/settlements",
  getParentRoute: () => SellerRoute,
} as any);
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: "/products/$id",
  path: "/products/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const DropsIdRoute = DropsIdRouteImport.update({
  id: "/drops/$id",
  path: "/drops/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminSettlementsRoute = AdminSettlementsRouteImport.update({
  id: "/settlements",
  path: "/settlements",
  getParentRoute: () => AdminRoute,
} as any);
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: "/categories",
  path: "/categories",
  getParentRoute: () => AdminRoute,
} as any);
const AuthedMypageRoute = AuthedMypageRouteImport.update({
  id: "/mypage",
  path: "/mypage",
  getParentRoute: () => AuthedRoute,
} as any);
const SellerProductsIndexRoute = SellerProductsIndexRouteImport.update({
  id: "/products/",
  path: "/products/",
  getParentRoute: () => SellerRoute,
} as any);
const AuthedOrdersIndexRoute = AuthedOrdersIndexRouteImport.update({
  id: "/orders/",
  path: "/orders/",
  getParentRoute: () => AuthedRoute,
} as any);
const SellerProductsNewRoute = SellerProductsNewRouteImport.update({
  id: "/products/new",
  path: "/products/new",
  getParentRoute: () => SellerRoute,
} as any);
const SellerProductsIdRoute = SellerProductsIdRouteImport.update({
  id: "/products/$id",
  path: "/products/$id",
  getParentRoute: () => SellerRoute,
} as any);
const AuthedCheckoutOrderIdRoute = AuthedCheckoutOrderIdRouteImport.update({
  id: "/checkout/$orderId",
  path: "/checkout/$orderId",
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedOrdersOrderIdIndexRoute =
  AuthedOrdersOrderIdIndexRouteImport.update({
    id: "/orders/$orderId/",
    path: "/orders/$orderId/",
    getParentRoute: () => AuthedRoute,
  } as any);
const AuthedOrdersOrderIdCompleteRoute =
  AuthedOrdersOrderIdCompleteRouteImport.update({
    id: "/orders/$orderId/complete",
    path: "/orders/$orderId/complete",
    getParentRoute: () => AuthedRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/admin": typeof AdminRouteWithChildren;
  "/forbidden": typeof ForbiddenRoute;
  "/login": typeof LoginRoute;
  "/seller": typeof SellerRouteWithChildren;
  "/signup": typeof SignupRoute;
  "/mypage": typeof AuthedMypageRoute;
  "/admin/categories": typeof AdminCategoriesRoute;
  "/admin/settlements": typeof AdminSettlementsRoute;
  "/drops/$id": typeof DropsIdRoute;
  "/products/$id": typeof ProductsIdRoute;
  "/seller/settlements": typeof SellerSettlementsRoute;
  "/admin/": typeof AdminIndexRoute;
  "/drops/": typeof DropsIndexRoute;
  "/products/": typeof ProductsIndexRoute;
  "/checkout/$orderId": typeof AuthedCheckoutOrderIdRoute;
  "/seller/products/$id": typeof SellerProductsIdRoute;
  "/seller/products/new": typeof SellerProductsNewRoute;
  "/orders/": typeof AuthedOrdersIndexRoute;
  "/seller/products/": typeof SellerProductsIndexRoute;
  "/orders/$orderId/complete": typeof AuthedOrdersOrderIdCompleteRoute;
  "/orders/$orderId/": typeof AuthedOrdersOrderIdIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/forbidden": typeof ForbiddenRoute;
  "/login": typeof LoginRoute;
  "/seller": typeof SellerRouteWithChildren;
  "/signup": typeof SignupRoute;
  "/mypage": typeof AuthedMypageRoute;
  "/admin/categories": typeof AdminCategoriesRoute;
  "/admin/settlements": typeof AdminSettlementsRoute;
  "/drops/$id": typeof DropsIdRoute;
  "/products/$id": typeof ProductsIdRoute;
  "/seller/settlements": typeof SellerSettlementsRoute;
  "/admin": typeof AdminIndexRoute;
  "/drops": typeof DropsIndexRoute;
  "/products": typeof ProductsIndexRoute;
  "/checkout/$orderId": typeof AuthedCheckoutOrderIdRoute;
  "/seller/products/$id": typeof SellerProductsIdRoute;
  "/seller/products/new": typeof SellerProductsNewRoute;
  "/orders": typeof AuthedOrdersIndexRoute;
  "/seller/products": typeof SellerProductsIndexRoute;
  "/orders/$orderId/complete": typeof AuthedOrdersOrderIdCompleteRoute;
  "/orders/$orderId": typeof AuthedOrdersOrderIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_authed": typeof AuthedRouteWithChildren;
  "/admin": typeof AdminRouteWithChildren;
  "/forbidden": typeof ForbiddenRoute;
  "/login": typeof LoginRoute;
  "/seller": typeof SellerRouteWithChildren;
  "/signup": typeof SignupRoute;
  "/_authed/mypage": typeof AuthedMypageRoute;
  "/admin/categories": typeof AdminCategoriesRoute;
  "/admin/settlements": typeof AdminSettlementsRoute;
  "/drops/$id": typeof DropsIdRoute;
  "/products/$id": typeof ProductsIdRoute;
  "/seller/settlements": typeof SellerSettlementsRoute;
  "/admin/": typeof AdminIndexRoute;
  "/drops/": typeof DropsIndexRoute;
  "/products/": typeof ProductsIndexRoute;
  "/_authed/checkout/$orderId": typeof AuthedCheckoutOrderIdRoute;
  "/seller/products/$id": typeof SellerProductsIdRoute;
  "/seller/products/new": typeof SellerProductsNewRoute;
  "/_authed/orders/": typeof AuthedOrdersIndexRoute;
  "/seller/products/": typeof SellerProductsIndexRoute;
  "/_authed/orders/$orderId/complete": typeof AuthedOrdersOrderIdCompleteRoute;
  "/_authed/orders/$orderId/": typeof AuthedOrdersOrderIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/admin"
    | "/forbidden"
    | "/login"
    | "/seller"
    | "/signup"
    | "/mypage"
    | "/admin/categories"
    | "/admin/settlements"
    | "/drops/$id"
    | "/products/$id"
    | "/seller/settlements"
    | "/admin/"
    | "/drops/"
    | "/products/"
    | "/checkout/$orderId"
    | "/seller/products/$id"
    | "/seller/products/new"
    | "/orders/"
    | "/seller/products/"
    | "/orders/$orderId/complete"
    | "/orders/$orderId/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/forbidden"
    | "/login"
    | "/seller"
    | "/signup"
    | "/mypage"
    | "/admin/categories"
    | "/admin/settlements"
    | "/drops/$id"
    | "/products/$id"
    | "/seller/settlements"
    | "/admin"
    | "/drops"
    | "/products"
    | "/checkout/$orderId"
    | "/seller/products/$id"
    | "/seller/products/new"
    | "/orders"
    | "/seller/products"
    | "/orders/$orderId/complete"
    | "/orders/$orderId";
  id:
    | "__root__"
    | "/"
    | "/_authed"
    | "/admin"
    | "/forbidden"
    | "/login"
    | "/seller"
    | "/signup"
    | "/_authed/mypage"
    | "/admin/categories"
    | "/admin/settlements"
    | "/drops/$id"
    | "/products/$id"
    | "/seller/settlements"
    | "/admin/"
    | "/drops/"
    | "/products/"
    | "/_authed/checkout/$orderId"
    | "/seller/products/$id"
    | "/seller/products/new"
    | "/_authed/orders/"
    | "/seller/products/"
    | "/_authed/orders/$orderId/complete"
    | "/_authed/orders/$orderId/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthedRoute: typeof AuthedRouteWithChildren;
  AdminRoute: typeof AdminRouteWithChildren;
  ForbiddenRoute: typeof ForbiddenRoute;
  LoginRoute: typeof LoginRoute;
  SellerRoute: typeof SellerRouteWithChildren;
  SignupRoute: typeof SignupRoute;
  DropsIdRoute: typeof DropsIdRoute;
  ProductsIdRoute: typeof ProductsIdRoute;
  DropsIndexRoute: typeof DropsIndexRoute;
  ProductsIndexRoute: typeof ProductsIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/signup": {
      id: "/signup";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof SignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/seller": {
      id: "/seller";
      path: "/seller";
      fullPath: "/seller";
      preLoaderRoute: typeof SellerRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/forbidden": {
      id: "/forbidden";
      path: "/forbidden";
      fullPath: "/forbidden";
      preLoaderRoute: typeof ForbiddenRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin": {
      id: "/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AdminRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authed": {
      id: "/_authed";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/products/": {
      id: "/products/";
      path: "/products";
      fullPath: "/products/";
      preLoaderRoute: typeof ProductsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/drops/": {
      id: "/drops/";
      path: "/drops";
      fullPath: "/drops/";
      preLoaderRoute: typeof DropsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin/": {
      id: "/admin/";
      path: "/";
      fullPath: "/admin/";
      preLoaderRoute: typeof AdminIndexRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/seller/settlements": {
      id: "/seller/settlements";
      path: "/settlements";
      fullPath: "/seller/settlements";
      preLoaderRoute: typeof SellerSettlementsRouteImport;
      parentRoute: typeof SellerRoute;
    };
    "/products/$id": {
      id: "/products/$id";
      path: "/products/$id";
      fullPath: "/products/$id";
      preLoaderRoute: typeof ProductsIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/drops/$id": {
      id: "/drops/$id";
      path: "/drops/$id";
      fullPath: "/drops/$id";
      preLoaderRoute: typeof DropsIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin/settlements": {
      id: "/admin/settlements";
      path: "/settlements";
      fullPath: "/admin/settlements";
      preLoaderRoute: typeof AdminSettlementsRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/admin/categories": {
      id: "/admin/categories";
      path: "/categories";
      fullPath: "/admin/categories";
      preLoaderRoute: typeof AdminCategoriesRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/_authed/mypage": {
      id: "/_authed/mypage";
      path: "/mypage";
      fullPath: "/mypage";
      preLoaderRoute: typeof AuthedMypageRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/seller/products/": {
      id: "/seller/products/";
      path: "/products";
      fullPath: "/seller/products/";
      preLoaderRoute: typeof SellerProductsIndexRouteImport;
      parentRoute: typeof SellerRoute;
    };
    "/_authed/orders/": {
      id: "/_authed/orders/";
      path: "/orders";
      fullPath: "/orders/";
      preLoaderRoute: typeof AuthedOrdersIndexRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/seller/products/new": {
      id: "/seller/products/new";
      path: "/products/new";
      fullPath: "/seller/products/new";
      preLoaderRoute: typeof SellerProductsNewRouteImport;
      parentRoute: typeof SellerRoute;
    };
    "/seller/products/$id": {
      id: "/seller/products/$id";
      path: "/products/$id";
      fullPath: "/seller/products/$id";
      preLoaderRoute: typeof SellerProductsIdRouteImport;
      parentRoute: typeof SellerRoute;
    };
    "/_authed/checkout/$orderId": {
      id: "/_authed/checkout/$orderId";
      path: "/checkout/$orderId";
      fullPath: "/checkout/$orderId";
      preLoaderRoute: typeof AuthedCheckoutOrderIdRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/orders/$orderId/": {
      id: "/_authed/orders/$orderId/";
      path: "/orders/$orderId";
      fullPath: "/orders/$orderId/";
      preLoaderRoute: typeof AuthedOrdersOrderIdIndexRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/orders/$orderId/complete": {
      id: "/_authed/orders/$orderId/complete";
      path: "/orders/$orderId/complete";
      fullPath: "/orders/$orderId/complete";
      preLoaderRoute: typeof AuthedOrdersOrderIdCompleteRouteImport;
      parentRoute: typeof AuthedRoute;
    };
  }
}

interface AuthedRouteChildren {
  AuthedMypageRoute: typeof AuthedMypageRoute;
  AuthedCheckoutOrderIdRoute: typeof AuthedCheckoutOrderIdRoute;
  AuthedOrdersIndexRoute: typeof AuthedOrdersIndexRoute;
  AuthedOrdersOrderIdCompleteRoute: typeof AuthedOrdersOrderIdCompleteRoute;
  AuthedOrdersOrderIdIndexRoute: typeof AuthedOrdersOrderIdIndexRoute;
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedMypageRoute: AuthedMypageRoute,
  AuthedCheckoutOrderIdRoute: AuthedCheckoutOrderIdRoute,
  AuthedOrdersIndexRoute: AuthedOrdersIndexRoute,
  AuthedOrdersOrderIdCompleteRoute: AuthedOrdersOrderIdCompleteRoute,
  AuthedOrdersOrderIdIndexRoute: AuthedOrdersOrderIdIndexRoute,
};

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren);

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute;
  AdminSettlementsRoute: typeof AdminSettlementsRoute;
  AdminIndexRoute: typeof AdminIndexRoute;
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminSettlementsRoute: AdminSettlementsRoute,
  AdminIndexRoute: AdminIndexRoute,
};

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren);

interface SellerRouteChildren {
  SellerSettlementsRoute: typeof SellerSettlementsRoute;
  SellerProductsIdRoute: typeof SellerProductsIdRoute;
  SellerProductsNewRoute: typeof SellerProductsNewRoute;
  SellerProductsIndexRoute: typeof SellerProductsIndexRoute;
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerSettlementsRoute: SellerSettlementsRoute,
  SellerProductsIdRoute: SellerProductsIdRoute,
  SellerProductsNewRoute: SellerProductsNewRoute,
  SellerProductsIndexRoute: SellerProductsIndexRoute,
};

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
  SellerRoute: SellerRouteWithChildren,
  SignupRoute: SignupRoute,
  DropsIdRoute: DropsIdRoute,
  ProductsIdRoute: ProductsIdRoute,
  DropsIndexRoute: DropsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
