/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ProductsIndexRouteImport } from "./routes/products/index";
import { Route as DropsIndexRouteImport } from "./routes/drops/index";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: "/products/",
  path: "/products/",
  getParentRoute: () => rootRouteImport,
} as any);
const DropsIndexRoute = DropsIndexRouteImport.update({
  id: "/drops/",
  path: "/drops/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/drops/": typeof DropsIndexRoute;
  "/products/": typeof ProductsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/drops": typeof DropsIndexRoute;
  "/products": typeof ProductsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/drops/": typeof DropsIndexRoute;
  "/products/": typeof ProductsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/drops/" | "/products/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/drops" | "/products";
  id: "__root__" | "/" | "/drops/" | "/products/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DropsIndexRoute: typeof DropsIndexRoute;
  ProductsIndexRoute: typeof ProductsIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/products/": {
      id: "/products/";
      path: "/products";
      fullPath: "/products/";
      preLoaderRoute: typeof ProductsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/drops/": {
      id: "/drops/";
      path: "/drops";
      fullPath: "/drops/";
      preLoaderRoute: typeof DropsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DropsIndexRoute: DropsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
