/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SignupRouteImport } from "./routes/signup";
import { Route as MypageRouteImport } from "./routes/mypage";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ProductsIndexRouteImport } from "./routes/products/index";
import { Route as OrdersIndexRouteImport } from "./routes/orders/index";
import { Route as DropsIndexRouteImport } from "./routes/drops/index";
import { Route as AdminIndexRouteImport } from "./routes/admin/index";
import { Route as SellerSettlementsRouteImport } from "./routes/seller/settlements";
import { Route as ProductsIdRouteImport } from "./routes/products/$id";
import { Route as DropsIdRouteImport } from "./routes/drops/$id";
import { Route as CheckoutOrderIdRouteImport } from "./routes/checkout/$orderId";
import { Route as AdminSettlementsRouteImport } from "./routes/admin/settlements";
import { Route as AdminCategoriesRouteImport } from "./routes/admin/categories";
import { Route as SellerProductsIndexRouteImport } from "./routes/seller/products/index";
import { Route as OrdersOrderIdIndexRouteImport } from "./routes/orders/$orderId/index";
import { Route as TossPaymentSuccessRouteImport } from "./routes/toss/payment/success";
import { Route as TossChargeSuccessRouteImport } from "./routes/toss/charge/success";
import { Route as SellerProductsNewRouteImport } from "./routes/seller/products/new";
import { Route as SellerProductsIdRouteImport } from "./routes/seller/products/$id";
import { Route as OrdersOrderIdCompleteRouteImport } from "./routes/orders/$orderId/complete";

const SignupRoute = SignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRouteImport,
} as any);
const MypageRoute = MypageRouteImport.update({
  id: "/mypage",
  path: "/mypage",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: "/products/",
  path: "/products/",
  getParentRoute: () => rootRouteImport,
} as any);
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: "/orders/",
  path: "/orders/",
  getParentRoute: () => rootRouteImport,
} as any);
const DropsIndexRoute = DropsIndexRouteImport.update({
  id: "/drops/",
  path: "/drops/",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/admin/",
  path: "/admin/",
  getParentRoute: () => rootRouteImport,
} as any);
const SellerSettlementsRoute = SellerSettlementsRouteImport.update({
  id: "/seller/settlements",
  path: "/seller/settlements",
  getParentRoute: () => rootRouteImport,
} as any);
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: "/products/$id",
  path: "/products/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const DropsIdRoute = DropsIdRouteImport.update({
  id: "/drops/$id",
  path: "/drops/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const CheckoutOrderIdRoute = CheckoutOrderIdRouteImport.update({
  id: "/checkout/$orderId",
  path: "/checkout/$orderId",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminSettlementsRoute = AdminSettlementsRouteImport.update({
  id: "/admin/settlements",
  path: "/admin/settlements",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: "/admin/categories",
  path: "/admin/categories",
  getParentRoute: () => rootRouteImport,
} as any);
const SellerProductsIndexRoute = SellerProductsIndexRouteImport.update({
  id: "/seller/products/",
  path: "/seller/products/",
  getParentRoute: () => rootRouteImport,
} as any);
const OrdersOrderIdIndexRoute = OrdersOrderIdIndexRouteImport.update({
  id: "/orders/$orderId/",
  path: "/orders/$orderId/",
  getParentRoute: () => rootRouteImport,
} as any);
const TossPaymentSuccessRoute = TossPaymentSuccessRouteImport.update({
  id: "/toss/payment/success",
  path: "/toss/payment/success",
  getParentRoute: () => rootRouteImport,
} as any);
const TossChargeSuccessRoute = TossChargeSuccessRouteImport.update({
  id: "/toss/charge/success",
  path: "/toss/charge/success",
  getParentRoute: () => rootRouteImport,
} as any);
const SellerProductsNewRoute = SellerProductsNewRouteImport.update({
  id: "/seller/products/new",
  path: "/seller/products/new",
  getParentRoute: () => rootRouteImport,
} as any);
const SellerProductsIdRoute = SellerProductsIdRouteImport.update({
  id: "/seller/products/$id",
  path: "/seller/products/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const OrdersOrderIdCompleteRoute = OrdersOrderIdCompleteRouteImport.update({
  id: "/orders/$orderId/complete",
  path: "/orders/$orderId/complete",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/mypage": typeof MypageRoute;
  "/signup": typeof SignupRoute;
  "/admin/categories": typeof AdminCategoriesRoute;
  "/admin/settlements": typeof AdminSettlementsRoute;
  "/checkout/$orderId": typeof CheckoutOrderIdRoute;
  "/drops/$id": typeof DropsIdRoute;
  "/products/$id": typeof ProductsIdRoute;
  "/seller/settlements": typeof SellerSettlementsRoute;
  "/admin/": typeof AdminIndexRoute;
  "/drops/": typeof DropsIndexRoute;
  "/orders/": typeof OrdersIndexRoute;
  "/products/": typeof ProductsIndexRoute;
  "/orders/$orderId/complete": typeof OrdersOrderIdCompleteRoute;
  "/seller/products/$id": typeof SellerProductsIdRoute;
  "/seller/products/new": typeof SellerProductsNewRoute;
  "/toss/charge/success": typeof TossChargeSuccessRoute;
  "/toss/payment/success": typeof TossPaymentSuccessRoute;
  "/orders/$orderId/": typeof OrdersOrderIdIndexRoute;
  "/seller/products/": typeof SellerProductsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/mypage": typeof MypageRoute;
  "/signup": typeof SignupRoute;
  "/admin/categories": typeof AdminCategoriesRoute;
  "/admin/settlements": typeof AdminSettlementsRoute;
  "/checkout/$orderId": typeof CheckoutOrderIdRoute;
  "/drops/$id": typeof DropsIdRoute;
  "/products/$id": typeof ProductsIdRoute;
  "/seller/settlements": typeof SellerSettlementsRoute;
  "/admin": typeof AdminIndexRoute;
  "/drops": typeof DropsIndexRoute;
  "/orders": typeof OrdersIndexRoute;
  "/products": typeof ProductsIndexRoute;
  "/orders/$orderId/complete": typeof OrdersOrderIdCompleteRoute;
  "/seller/products/$id": typeof SellerProductsIdRoute;
  "/seller/products/new": typeof SellerProductsNewRoute;
  "/toss/charge/success": typeof TossChargeSuccessRoute;
  "/toss/payment/success": typeof TossPaymentSuccessRoute;
  "/orders/$orderId": typeof OrdersOrderIdIndexRoute;
  "/seller/products": typeof SellerProductsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/mypage": typeof MypageRoute;
  "/signup": typeof SignupRoute;
  "/admin/categories": typeof AdminCategoriesRoute;
  "/admin/settlements": typeof AdminSettlementsRoute;
  "/checkout/$orderId": typeof CheckoutOrderIdRoute;
  "/drops/$id": typeof DropsIdRoute;
  "/products/$id": typeof ProductsIdRoute;
  "/seller/settlements": typeof SellerSettlementsRoute;
  "/admin/": typeof AdminIndexRoute;
  "/drops/": typeof DropsIndexRoute;
  "/orders/": typeof OrdersIndexRoute;
  "/products/": typeof ProductsIndexRoute;
  "/orders/$orderId/complete": typeof OrdersOrderIdCompleteRoute;
  "/seller/products/$id": typeof SellerProductsIdRoute;
  "/seller/products/new": typeof SellerProductsNewRoute;
  "/toss/charge/success": typeof TossChargeSuccessRoute;
  "/toss/payment/success": typeof TossPaymentSuccessRoute;
  "/orders/$orderId/": typeof OrdersOrderIdIndexRoute;
  "/seller/products/": typeof SellerProductsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login"
    | "/mypage"
    | "/signup"
    | "/admin/categories"
    | "/admin/settlements"
    | "/checkout/$orderId"
    | "/drops/$id"
    | "/products/$id"
    | "/seller/settlements"
    | "/admin/"
    | "/drops/"
    | "/orders/"
    | "/products/"
    | "/orders/$orderId/complete"
    | "/seller/products/$id"
    | "/seller/products/new"
    | "/toss/charge/success"
    | "/toss/payment/success"
    | "/orders/$orderId/"
    | "/seller/products/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/login"
    | "/mypage"
    | "/signup"
    | "/admin/categories"
    | "/admin/settlements"
    | "/checkout/$orderId"
    | "/drops/$id"
    | "/products/$id"
    | "/seller/settlements"
    | "/admin"
    | "/drops"
    | "/orders"
    | "/products"
    | "/orders/$orderId/complete"
    | "/seller/products/$id"
    | "/seller/products/new"
    | "/toss/charge/success"
    | "/toss/payment/success"
    | "/orders/$orderId"
    | "/seller/products";
  id:
    | "__root__"
    | "/"
    | "/login"
    | "/mypage"
    | "/signup"
    | "/admin/categories"
    | "/admin/settlements"
    | "/checkout/$orderId"
    | "/drops/$id"
    | "/products/$id"
    | "/seller/settlements"
    | "/admin/"
    | "/drops/"
    | "/orders/"
    | "/products/"
    | "/orders/$orderId/complete"
    | "/seller/products/$id"
    | "/seller/products/new"
    | "/toss/charge/success"
    | "/toss/payment/success"
    | "/orders/$orderId/"
    | "/seller/products/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  LoginRoute: typeof LoginRoute;
  MypageRoute: typeof MypageRoute;
  SignupRoute: typeof SignupRoute;
  AdminCategoriesRoute: typeof AdminCategoriesRoute;
  AdminSettlementsRoute: typeof AdminSettlementsRoute;
  CheckoutOrderIdRoute: typeof CheckoutOrderIdRoute;
  DropsIdRoute: typeof DropsIdRoute;
  ProductsIdRoute: typeof ProductsIdRoute;
  SellerSettlementsRoute: typeof SellerSettlementsRoute;
  AdminIndexRoute: typeof AdminIndexRoute;
  DropsIndexRoute: typeof DropsIndexRoute;
  OrdersIndexRoute: typeof OrdersIndexRoute;
  ProductsIndexRoute: typeof ProductsIndexRoute;
  OrdersOrderIdCompleteRoute: typeof OrdersOrderIdCompleteRoute;
  SellerProductsIdRoute: typeof SellerProductsIdRoute;
  SellerProductsNewRoute: typeof SellerProductsNewRoute;
  TossChargeSuccessRoute: typeof TossChargeSuccessRoute;
  TossPaymentSuccessRoute: typeof TossPaymentSuccessRoute;
  OrdersOrderIdIndexRoute: typeof OrdersOrderIdIndexRoute;
  SellerProductsIndexRoute: typeof SellerProductsIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/signup": {
      id: "/signup";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof SignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/mypage": {
      id: "/mypage";
      path: "/mypage";
      fullPath: "/mypage";
      preLoaderRoute: typeof MypageRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/products/": {
      id: "/products/";
      path: "/products";
      fullPath: "/products/";
      preLoaderRoute: typeof ProductsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/orders/": {
      id: "/orders/";
      path: "/orders";
      fullPath: "/orders/";
      preLoaderRoute: typeof OrdersIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/drops/": {
      id: "/drops/";
      path: "/drops";
      fullPath: "/drops/";
      preLoaderRoute: typeof DropsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin/": {
      id: "/admin/";
      path: "/admin";
      fullPath: "/admin/";
      preLoaderRoute: typeof AdminIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/seller/settlements": {
      id: "/seller/settlements";
      path: "/seller/settlements";
      fullPath: "/seller/settlements";
      preLoaderRoute: typeof SellerSettlementsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/products/$id": {
      id: "/products/$id";
      path: "/products/$id";
      fullPath: "/products/$id";
      preLoaderRoute: typeof ProductsIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/drops/$id": {
      id: "/drops/$id";
      path: "/drops/$id";
      fullPath: "/drops/$id";
      preLoaderRoute: typeof DropsIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/checkout/$orderId": {
      id: "/checkout/$orderId";
      path: "/checkout/$orderId";
      fullPath: "/checkout/$orderId";
      preLoaderRoute: typeof CheckoutOrderIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin/settlements": {
      id: "/admin/settlements";
      path: "/admin/settlements";
      fullPath: "/admin/settlements";
      preLoaderRoute: typeof AdminSettlementsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin/categories": {
      id: "/admin/categories";
      path: "/admin/categories";
      fullPath: "/admin/categories";
      preLoaderRoute: typeof AdminCategoriesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/seller/products/": {
      id: "/seller/products/";
      path: "/seller/products";
      fullPath: "/seller/products/";
      preLoaderRoute: typeof SellerProductsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/orders/$orderId/": {
      id: "/orders/$orderId/";
      path: "/orders/$orderId";
      fullPath: "/orders/$orderId/";
      preLoaderRoute: typeof OrdersOrderIdIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/toss/payment/success": {
      id: "/toss/payment/success";
      path: "/toss/payment/success";
      fullPath: "/toss/payment/success";
      preLoaderRoute: typeof TossPaymentSuccessRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/toss/charge/success": {
      id: "/toss/charge/success";
      path: "/toss/charge/success";
      fullPath: "/toss/charge/success";
      preLoaderRoute: typeof TossChargeSuccessRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/seller/products/new": {
      id: "/seller/products/new";
      path: "/seller/products/new";
      fullPath: "/seller/products/new";
      preLoaderRoute: typeof SellerProductsNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/seller/products/$id": {
      id: "/seller/products/$id";
      path: "/seller/products/$id";
      fullPath: "/seller/products/$id";
      preLoaderRoute: typeof SellerProductsIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/orders/$orderId/complete": {
      id: "/orders/$orderId/complete";
      path: "/orders/$orderId/complete";
      fullPath: "/orders/$orderId/complete";
      preLoaderRoute: typeof OrdersOrderIdCompleteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MypageRoute: MypageRoute,
  SignupRoute: SignupRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminSettlementsRoute: AdminSettlementsRoute,
  CheckoutOrderIdRoute: CheckoutOrderIdRoute,
  DropsIdRoute: DropsIdRoute,
  ProductsIdRoute: ProductsIdRoute,
  SellerSettlementsRoute: SellerSettlementsRoute,
  AdminIndexRoute: AdminIndexRoute,
  DropsIndexRoute: DropsIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  OrdersOrderIdCompleteRoute: OrdersOrderIdCompleteRoute,
  SellerProductsIdRoute: SellerProductsIdRoute,
  SellerProductsNewRoute: SellerProductsNewRoute,
  TossChargeSuccessRoute: TossChargeSuccessRoute,
  TossPaymentSuccessRoute: TossPaymentSuccessRoute,
  OrdersOrderIdIndexRoute: OrdersOrderIdIndexRoute,
  SellerProductsIndexRoute: SellerProductsIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
